/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsIndexRouteImport } from './routes/documents/index'
import { Route as TextblocksNewRouteImport } from './routes/textblocks/new'
import { Route as TextblocksBlockIdRouteImport } from './routes/textblocks/$blockId'
import { Route as RulesNewRouteImport } from './routes/rules/new'
import { Route as RulesRuleIdRouteImport } from './routes/rules/$ruleId'
import { Route as DocumentsNewRouteImport } from './routes/documents/new'
import { Route as CollectionsNewRouteImport } from './routes/collections/new'
import { Route as DocumentsIdIndexRouteImport } from './routes/documents/$id/index'
import { Route as CollectionsCollectionIdIndexRouteImport } from './routes/collections/$collectionId/index'
import { Route as DocumentsIdRulesRouteImport } from './routes/documents/$id/rules'
import { Route as DocumentsIdEditRouteImport } from './routes/documents/$id/edit'
import { Route as DocumentsIdBlocksRouteImport } from './routes/documents/$id/blocks'
import { Route as CollectionsCollectionIdDownloadRouteImport } from './routes/collections/$collectionId/download'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextblocksNewRoute = TextblocksNewRouteImport.update({
  id: '/textblocks/new',
  path: '/textblocks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TextblocksBlockIdRoute = TextblocksBlockIdRouteImport.update({
  id: '/textblocks/$blockId',
  path: '/textblocks/$blockId',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesNewRoute = RulesNewRouteImport.update({
  id: '/rules/new',
  path: '/rules/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRuleIdRoute = RulesRuleIdRouteImport.update({
  id: '/rules/$ruleId',
  path: '/rules/$ruleId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsNewRoute = DocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsNewRoute = CollectionsNewRouteImport.update({
  id: '/collections/new',
  path: '/collections/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIdIndexRoute = DocumentsIdIndexRouteImport.update({
  id: '/documents/$id/',
  path: '/documents/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdIndexRoute =
  CollectionsCollectionIdIndexRouteImport.update({
    id: '/collections/$collectionId/',
    path: '/collections/$collectionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsIdRulesRoute = DocumentsIdRulesRouteImport.update({
  id: '/documents/$id/rules',
  path: '/documents/$id/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIdEditRoute = DocumentsIdEditRouteImport.update({
  id: '/documents/$id/edit',
  path: '/documents/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIdBlocksRoute = DocumentsIdBlocksRouteImport.update({
  id: '/documents/$id/blocks',
  path: '/documents/$id/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdDownloadRoute =
  CollectionsCollectionIdDownloadRouteImport.update({
    id: '/collections/$collectionId/download',
    path: '/collections/$collectionId/download',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections/new': typeof CollectionsNewRoute
  '/documents/new': typeof DocumentsNewRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/rules/new': typeof RulesNewRoute
  '/textblocks/$blockId': typeof TextblocksBlockIdRoute
  '/textblocks/new': typeof TextblocksNewRoute
  '/documents': typeof DocumentsIndexRoute
  '/collections/$collectionId/download': typeof CollectionsCollectionIdDownloadRoute
  '/documents/$id/blocks': typeof DocumentsIdBlocksRoute
  '/documents/$id/edit': typeof DocumentsIdEditRoute
  '/documents/$id/rules': typeof DocumentsIdRulesRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdIndexRoute
  '/documents/$id': typeof DocumentsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections/new': typeof CollectionsNewRoute
  '/documents/new': typeof DocumentsNewRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/rules/new': typeof RulesNewRoute
  '/textblocks/$blockId': typeof TextblocksBlockIdRoute
  '/textblocks/new': typeof TextblocksNewRoute
  '/documents': typeof DocumentsIndexRoute
  '/collections/$collectionId/download': typeof CollectionsCollectionIdDownloadRoute
  '/documents/$id/blocks': typeof DocumentsIdBlocksRoute
  '/documents/$id/edit': typeof DocumentsIdEditRoute
  '/documents/$id/rules': typeof DocumentsIdRulesRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdIndexRoute
  '/documents/$id': typeof DocumentsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections/new': typeof CollectionsNewRoute
  '/documents/new': typeof DocumentsNewRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/rules/new': typeof RulesNewRoute
  '/textblocks/$blockId': typeof TextblocksBlockIdRoute
  '/textblocks/new': typeof TextblocksNewRoute
  '/documents/': typeof DocumentsIndexRoute
  '/collections/$collectionId/download': typeof CollectionsCollectionIdDownloadRoute
  '/documents/$id/blocks': typeof DocumentsIdBlocksRoute
  '/documents/$id/edit': typeof DocumentsIdEditRoute
  '/documents/$id/rules': typeof DocumentsIdRulesRoute
  '/collections/$collectionId/': typeof CollectionsCollectionIdIndexRoute
  '/documents/$id/': typeof DocumentsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections/new'
    | '/documents/new'
    | '/rules/$ruleId'
    | '/rules/new'
    | '/textblocks/$blockId'
    | '/textblocks/new'
    | '/documents'
    | '/collections/$collectionId/download'
    | '/documents/$id/blocks'
    | '/documents/$id/edit'
    | '/documents/$id/rules'
    | '/collections/$collectionId'
    | '/documents/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections/new'
    | '/documents/new'
    | '/rules/$ruleId'
    | '/rules/new'
    | '/textblocks/$blockId'
    | '/textblocks/new'
    | '/documents'
    | '/collections/$collectionId/download'
    | '/documents/$id/blocks'
    | '/documents/$id/edit'
    | '/documents/$id/rules'
    | '/collections/$collectionId'
    | '/documents/$id'
  id:
    | '__root__'
    | '/'
    | '/collections/new'
    | '/documents/new'
    | '/rules/$ruleId'
    | '/rules/new'
    | '/textblocks/$blockId'
    | '/textblocks/new'
    | '/documents/'
    | '/collections/$collectionId/download'
    | '/documents/$id/blocks'
    | '/documents/$id/edit'
    | '/documents/$id/rules'
    | '/collections/$collectionId/'
    | '/documents/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsNewRoute: typeof CollectionsNewRoute
  DocumentsNewRoute: typeof DocumentsNewRoute
  RulesRuleIdRoute: typeof RulesRuleIdRoute
  RulesNewRoute: typeof RulesNewRoute
  TextblocksBlockIdRoute: typeof TextblocksBlockIdRoute
  TextblocksNewRoute: typeof TextblocksNewRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  CollectionsCollectionIdDownloadRoute: typeof CollectionsCollectionIdDownloadRoute
  DocumentsIdBlocksRoute: typeof DocumentsIdBlocksRoute
  DocumentsIdEditRoute: typeof DocumentsIdEditRoute
  DocumentsIdRulesRoute: typeof DocumentsIdRulesRoute
  CollectionsCollectionIdIndexRoute: typeof CollectionsCollectionIdIndexRoute
  DocumentsIdIndexRoute: typeof DocumentsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/textblocks/new': {
      id: '/textblocks/new'
      path: '/textblocks/new'
      fullPath: '/textblocks/new'
      preLoaderRoute: typeof TextblocksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/textblocks/$blockId': {
      id: '/textblocks/$blockId'
      path: '/textblocks/$blockId'
      fullPath: '/textblocks/$blockId'
      preLoaderRoute: typeof TextblocksBlockIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/new': {
      id: '/rules/new'
      path: '/rules/new'
      fullPath: '/rules/new'
      preLoaderRoute: typeof RulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$ruleId': {
      id: '/rules/$ruleId'
      path: '/rules/$ruleId'
      fullPath: '/rules/$ruleId'
      preLoaderRoute: typeof RulesRuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/new': {
      id: '/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof DocumentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/new': {
      id: '/collections/new'
      path: '/collections/new'
      fullPath: '/collections/new'
      preLoaderRoute: typeof CollectionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$id/': {
      id: '/documents/$id/'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId/': {
      id: '/collections/$collectionId/'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$id/rules': {
      id: '/documents/$id/rules'
      path: '/documents/$id/rules'
      fullPath: '/documents/$id/rules'
      preLoaderRoute: typeof DocumentsIdRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$id/edit': {
      id: '/documents/$id/edit'
      path: '/documents/$id/edit'
      fullPath: '/documents/$id/edit'
      preLoaderRoute: typeof DocumentsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$id/blocks': {
      id: '/documents/$id/blocks'
      path: '/documents/$id/blocks'
      fullPath: '/documents/$id/blocks'
      preLoaderRoute: typeof DocumentsIdBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId/download': {
      id: '/collections/$collectionId/download'
      path: '/collections/$collectionId/download'
      fullPath: '/collections/$collectionId/download'
      preLoaderRoute: typeof CollectionsCollectionIdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsNewRoute: CollectionsNewRoute,
  DocumentsNewRoute: DocumentsNewRoute,
  RulesRuleIdRoute: RulesRuleIdRoute,
  RulesNewRoute: RulesNewRoute,
  TextblocksBlockIdRoute: TextblocksBlockIdRoute,
  TextblocksNewRoute: TextblocksNewRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  CollectionsCollectionIdDownloadRoute: CollectionsCollectionIdDownloadRoute,
  DocumentsIdBlocksRoute: DocumentsIdBlocksRoute,
  DocumentsIdEditRoute: DocumentsIdEditRoute,
  DocumentsIdRulesRoute: DocumentsIdRulesRoute,
  CollectionsCollectionIdIndexRoute: CollectionsCollectionIdIndexRoute,
  DocumentsIdIndexRoute: DocumentsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
